export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_CODE: "INVALID_CODE",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  OAUTH_UNAVAILABLE: "OAUTH_UNAVAILABLE",
  OAUTH_FAILED: "OAUTH_FAILED",
  SAME_PASSWORD: "SAME_PASSWORD",
  PASSWORD_ALREADY_SET: "PASSWORD_ALREADY_SET",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
